<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ChatGroupInviteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $this->command?->info('Group invitation links are generated by group owners and are not seeded.');
    }
}
