@extends('layouts.app')
@section('bodyClass', 'workspace-full-page')
@section('title', 'Quiz Builder')
@section('styles')<link rel="stylesheet" href="{{ asset('css/quiz.css') }}">@endsection
@section('content')<div class="page-container quiz-page"><div class="quiz-hero"><div><span class="quiz-status">Draft</span><h1>{{ $quiz->title }}</h1><p>Build and preview your assessment before assigning it.</p></div><div class="quiz-actions"><a class="btn btn-light" href="{{ route('classes.quizzes.preview', [$schoolClass, $quiz]) }}">Preview</a>@if($quiz->questions->isNotEmpty())<form method="POST" action="{{ route('classes.quizzes.publish', [$schoolClass, $quiz]) }}">@csrf<button class="btn btn-primary">Publish & assign</button></form>@endif</div></div>
<form class="quiz-panel" method="POST" action="{{ route('classes.quizzes.update', [$schoolClass, $quiz]) }}">@csrf @method('PATCH')<div class="quiz-form-grid"><div><label class="form-label">Title</label><input class="form-control" name="title" value="{{ $quiz->title }}" required></div><div class="quiz-field-full"><label class="form-label">Description</label><textarea class="form-control" name="description">{{ $quiz->description }}</textarea></div></div><button class="btn btn-outline-primary mt-3">Save details</button></form>
<div class="quiz-panel"><div class="quiz-panel-title"><h2>Questions</h2><span>{{ $quiz->questions->count() }} · {{ number_format($quiz->questions->sum('points'), 2) }} points</span></div>@foreach($quiz->questions as $question)<article class="quiz-question-card"><div class="quiz-question-heading"><div><span class="quiz-status">{{ str_replace('_', ' ', $question->type) }}</span><h3 class="mt-2">{{ $loop->iteration }}. {{ $question->prompt }}</h3><small>{{ $question->points }} point(s) · {{ $question->grading_mode }}</small></div><div class="quiz-actions"><form method="POST" action="{{ route('classes.quizzes.questions.move', [$schoolClass, $quiz, $question, 'up']) }}">@csrf<button class="btn btn-sm btn-light" aria-label="Move up">↑</button></form><form method="POST" action="{{ route('classes.quizzes.questions.move', [$schoolClass, $quiz, $question, 'down']) }}">@csrf<button class="btn btn-sm btn-light" aria-label="Move down">↓</button></form><form method="POST" action="{{ route('classes.quizzes.questions.duplicate', [$schoolClass, $quiz, $question]) }}">@csrf<button class="btn btn-sm btn-outline-secondary">Duplicate</button></form><form method="POST" action="{{ route('classes.quizzes.questions.destroy', [$schoolClass, $quiz, $question]) }}" data-confirm-title="Delete question?">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></div></div><details class="mt-3"><summary>Edit question</summary><div class="quiz-question-body">@include('quizzes.partials.question-form', ['question' => $question])</div></details></article>@endforeach</div>
<div class="quiz-panel"><div class="quiz-panel-title"><h2>Add question</h2></div>@include('quizzes.partials.question-form')</div></div>@endsection
@section('scripts')<script src="{{ asset('js/quiz-builder.js') }}"></script>@endsection
