@extends('layouts.app')
@section('title', 'Assessments')
@section('styles')<link rel="stylesheet" href="{{ asset('css/quiz.css') }}">@endsection
@section('content')
<div class="page-container quiz-page">
    <div class="quiz-hero"><div><h1>Assessments</h1><p>{{ $schoolClass->name }} · {{ $teacher ? 'Create, assign, and review quizzes.' : 'Your quizzes and results in one place.' }}</p></div><div class="quiz-actions"><a class="btn btn-light" href="{{ route('classes.show', $schoolClass) }}">Back to class</a>@if($teacher && !$schoolClass->isArchived())<a class="btn btn-primary" href="{{ route('classes.quizzes.create', $schoolClass) }}"><i class="ti ti-plus"></i> New quiz</a>@endif</div></div>
    @if($teacher)
        <div class="quiz-panel"><div class="quiz-panel-title"><h2>Quiz library</h2><span>{{ $quizzes->count() }} quizzes</span></div><div class="quiz-grid">
            @forelse($quizzes as $quiz)<article class="quiz-card"><span class="quiz-status">{{ $quiz->status }}</span><h3 class="mt-2">{{ $quiz->title }}</h3><p class="text-muted">{{ Str::limit($quiz->description ?: 'No description', 110) }}</p><div class="quiz-card-meta"><span>{{ $quiz->questions_count }} questions</span><span>{{ number_format($quiz->totalPoints(), 2) }} points</span><span>{{ $quiz->assignments->count() }} assignment(s)</span></div><div class="quiz-actions">@if(!$quiz->isLocked())<a class="btn btn-sm btn-primary" href="{{ route('classes.quizzes.edit', [$schoolClass, $quiz]) }}">Edit</a>@endif<a class="btn btn-sm btn-outline-secondary" href="{{ route('classes.quizzes.preview', [$schoolClass, $quiz]) }}">Preview</a>@if($quiz->status === 'published')<a class="btn btn-sm btn-outline-primary" href="{{ route('classes.quizzes.assign.create', [$schoolClass, $quiz]) }}">Assign</a>@endif</div></article>
            @empty<div class="quiz-empty quiz-field-full">Create your first quiz for this class.</div>@endforelse
        </div></div>
        <div class="quiz-panel"><div class="quiz-panel-title"><h2>Assigned quizzes</h2><span>{{ $assignments->count() }} assignments</span></div><div class="quiz-grid">@forelse($assignments as $assignment)<article class="quiz-card"><span class="quiz-status {{ $assignment->availabilityStatus() }}">{{ $assignment->availabilityStatus() }}</span><h3 class="mt-2">{{ $assignment->quiz->title }}</h3><div class="quiz-card-meta"><span>{{ $assignment->students_count }} students</span><span>{{ $assignment->attempts_count }} attempts</span><span>Due {{ $assignment->due_at->format('M j, Y g:i A') }}</span></div><a class="btn btn-sm btn-primary" href="{{ route('classes.quiz-assignments.results', [$schoolClass, $assignment]) }}">View results</a></article>@empty<div class="quiz-empty quiz-field-full">Published quiz assignments will appear here.</div>@endforelse</div></div>
    @else
        <div class="quiz-grid">@forelse($assignments as $assignment)@php($attempt = $assignment->attempts->sortByDesc('attempt_number')->first())<article class="quiz-card"><span class="quiz-status {{ $attempt?->status ?? $assignment->availabilityStatus() }}">{{ str_replace('_', ' ', $attempt?->status ?? $assignment->availabilityStatus()) }}</span><h2 class="mt-2">{{ $assignment->quiz->title }}</h2><p class="text-muted">{{ $assignment->instructions ?: $assignment->quiz->description }}</p><div class="quiz-card-meta"><span>{{ $assignment->quiz->questions_count }} questions</span><span>{{ number_format($assignment->quiz->totalPoints(), 2) }} points</span><span>Due {{ $assignment->due_at->format('M j, Y g:i A') }}</span></div><div class="quiz-actions">@if($attempt?->status === 'in_progress')<a class="btn btn-primary" href="{{ route('classes.quiz-attempts.show', [$schoolClass, $attempt]) }}">Continue quiz</a>@elseif($attempt)<a class="btn btn-outline-primary" href="{{ route('classes.quiz-attempts.result', [$schoolClass, $attempt]) }}">View submission</a>@endif @if($assignment->availabilityStatus() === 'available' && $assignment->attempts->count() < $assignment->attempt_limit && $attempt?->status !== 'in_progress')<form method="POST" action="{{ route('classes.quiz-assignments.start', [$schoolClass, $assignment]) }}">@csrf<button class="btn btn-primary">{{ $attempt ? 'Start another attempt' : 'Start quiz' }}</button></form>@endif</div></article>@empty<div class="quiz-empty">You do not have any assigned quizzes yet.</div>@endforelse</div>
    @endif
</div>
@endsection
