@php($editing = isset($question))
<form method="POST" action="{{ $editing ? route('classes.quizzes.questions.update', [$schoolClass, $quiz, $question]) : route('classes.quizzes.questions.store', [$schoolClass, $quiz]) }}" data-question-form>
    @csrf @if($editing) @method('PATCH') @endif
    <div class="quiz-form-grid"><div><label class="form-label">Question type</label><select class="form-select" name="type" data-question-type><option value="multiple_choice" @selected(($question->type ?? '') === 'multiple_choice')>Multiple choice</option><option value="true_false" @selected(($question->type ?? '') === 'true_false')>True / False</option><option value="multiple_answer" @selected(($question->type ?? '') === 'multiple_answer')>Multiple answer</option><option value="short_answer" @selected(($question->type ?? '') === 'short_answer')>Short answer</option></select></div><div><label class="form-label">Points</label><input class="form-control" type="number" name="points" min="0.01" max="1000" step="0.01" value="{{ $question->points ?? 1 }}" required></div>
    <div class="quiz-field-full"><label class="form-label">Question</label><textarea class="form-control" name="prompt" rows="3" required>{{ $question->prompt ?? '' }}</textarea></div>
    <div><label class="form-label">Grading</label><select class="form-select" name="grading_mode"><option value="automatic" @selected(($question->grading_mode ?? '') === 'automatic')>Automatic</option><option value="manual" @selected(($question->grading_mode ?? '') === 'manual')>Manual review</option></select></div><div><label class="form-label">Explanation (optional)</label><input class="form-control" name="explanation" value="{{ $question->explanation ?? '' }}"></div>
    <div class="quiz-field-full" data-option-fields>@for($index = 0; $index < 4; $index++)@php($option = $editing ? $question->options->values()->get($index) : null)<div class="input-group mb-2"><span class="input-group-text"><input type="{{ ($question->type ?? 'multiple_choice') === 'multiple_answer' ? 'checkbox' : 'radio' }}" name="correct_options[]" value="{{ $index }}" @checked($option?->is_correct) data-correct-option></span><input class="form-control" name="options[{{ $index }}][text]" value="{{ $option?->text }}" placeholder="Option {{ $index + 1 }}"></div>@endfor</div>
    <div class="quiz-field-full" data-true-false-fields hidden><label class="form-label">Correct answer</label><select class="form-select" name="correct_options[]"><option value="1" @selected($editing && $question->options->firstWhere('text', 'True')?->is_correct)>True</option><option value="0" @selected($editing && $question->options->firstWhere('text', 'False')?->is_correct)>False</option></select></div>
    <div class="quiz-field-full" data-short-answer-fields hidden><label class="form-label">Accepted answers, one per line</label><textarea class="form-control" name="accepted_answers" rows="3">{{ $editing ? implode("\n", $question->accepted_answers ?? []) : '' }}</textarea><label class="mt-2"><input type="checkbox" name="case_sensitive" value="1" @checked($question->case_sensitive ?? false)> Case-sensitive automatic grading</label></div></div>
    <button class="btn btn-primary mt-3">{{ $editing ? 'Save question' : 'Add question' }}</button>
</form>
